version: "3"
services:
  dev:
    build: .
    image: hub.zidls.cn/imageserver:latest
    command: supervisord -c /code/deploy/pro_supervisord.conf
    container_name: image_server
    volumes:
      - .:/code
      - /data/imageServer:/data
    ports:
      - "9500:9500"
    environment:
      - PYTHONPATH=/code
    network_mode: bridge
