# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-20 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u56fe\u7247')),
                ('image_desc', models.CharField(default=b'', max_length=100, verbose_name='\u56fe\u7247\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u56fe\u7247\u5b58\u50a8',
                'verbose_name_plural': '\u56fe\u7247\u5b58\u50a8',
            },
        ),
    ]
